name = "trains"
description = "Shiny new project"
version = "0.0.0"

authors = ["Esther O'Keefe"]
maintainers = ["Esther O'Keefe <esthermations@gmail.com>"]
maintainers-logins = ["esthermations"]

executables = ["trains-main"]
